# MySql
version: '3.3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'mymoviedb'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'