export enum USER_ERROR {
  USER_INVALID_PAYLOAD = 'USER_INVALID_PAYLOAD',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
  USER_USERNAME_EXISTS = 'USER_USERNAME_EXISTS',
  USER_CREATE_ERROR = 'USER_CREATE_ERROR',
  USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
  USER_UNKNOWN_ERROR = 'USER_UNKNOWN_ERROR'
}

